/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  SystemSizes,
  SystemSpaces,
} from './utils/design-system';


export namespace Components {

  interface Cl2Up {}
  interface Cl2UpAttributes extends StencilHTMLAttributes {}

  interface ClAvatar {
    'spaces': SystemSpaces;
    'src': string;
  }
  interface ClAvatarAttributes extends StencilHTMLAttributes {
    'spaces'?: SystemSpaces;
    'src'?: string;
  }

  interface ClBox {
    'spaces': SystemSpaces;
  }
  interface ClBoxAttributes extends StencilHTMLAttributes {
    'spaces'?: SystemSpaces;
  }

  interface ClButtonBox {
    'spaces': SystemSpaces;
  }
  interface ClButtonBoxAttributes extends StencilHTMLAttributes {
    'onOnPressed'?: (event: CustomEvent) => void;
    'spaces'?: SystemSpaces;
  }

  interface ClExpansionPanel {}
  interface ClExpansionPanelAttributes extends StencilHTMLAttributes {
    'onOnToggled'?: (event: CustomEvent) => void;
  }

  interface ClHeading {}
  interface ClHeadingAttributes extends StencilHTMLAttributes {}

  interface ClPaper {
    'isInvisible': boolean;
    'spaces': SystemSpaces;
  }
  interface ClPaperAttributes extends StencilHTMLAttributes {
    'isInvisible'?: boolean;
    'spaces'?: SystemSpaces;
  }

  interface ClText {
    'size': SystemSizes;
    'weight': 'light' | 'bold';
  }
  interface ClTextAttributes extends StencilHTMLAttributes {
    'size'?: SystemSizes;
    'weight'?: 'light' | 'bold';
  }

  interface ClWeatherCard {
    'details': string;
    'location': string;
    'src': string;
    'temperature': string;
  }
  interface ClWeatherCardAttributes extends StencilHTMLAttributes {
    'details'?: string;
    'location'?: string;
    'src'?: string;
    'temperature'?: string;
  }

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'Cl2Up': Components.Cl2Up;
    'ClAvatar': Components.ClAvatar;
    'ClBox': Components.ClBox;
    'ClButtonBox': Components.ClButtonBox;
    'ClExpansionPanel': Components.ClExpansionPanel;
    'ClHeading': Components.ClHeading;
    'ClPaper': Components.ClPaper;
    'ClText': Components.ClText;
    'ClWeatherCard': Components.ClWeatherCard;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'cl-2-up': Components.Cl2UpAttributes;
    'cl-avatar': Components.ClAvatarAttributes;
    'cl-box': Components.ClBoxAttributes;
    'cl-button-box': Components.ClButtonBoxAttributes;
    'cl-expansion-panel': Components.ClExpansionPanelAttributes;
    'cl-heading': Components.ClHeadingAttributes;
    'cl-paper': Components.ClPaperAttributes;
    'cl-text': Components.ClTextAttributes;
    'cl-weather-card': Components.ClWeatherCardAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLCl2UpElement extends Components.Cl2Up, HTMLStencilElement {}
  var HTMLCl2UpElement: {
    prototype: HTMLCl2UpElement;
    new (): HTMLCl2UpElement;
  };

  interface HTMLClAvatarElement extends Components.ClAvatar, HTMLStencilElement {}
  var HTMLClAvatarElement: {
    prototype: HTMLClAvatarElement;
    new (): HTMLClAvatarElement;
  };

  interface HTMLClBoxElement extends Components.ClBox, HTMLStencilElement {}
  var HTMLClBoxElement: {
    prototype: HTMLClBoxElement;
    new (): HTMLClBoxElement;
  };

  interface HTMLClButtonBoxElement extends Components.ClButtonBox, HTMLStencilElement {}
  var HTMLClButtonBoxElement: {
    prototype: HTMLClButtonBoxElement;
    new (): HTMLClButtonBoxElement;
  };

  interface HTMLClExpansionPanelElement extends Components.ClExpansionPanel, HTMLStencilElement {}
  var HTMLClExpansionPanelElement: {
    prototype: HTMLClExpansionPanelElement;
    new (): HTMLClExpansionPanelElement;
  };

  interface HTMLClHeadingElement extends Components.ClHeading, HTMLStencilElement {}
  var HTMLClHeadingElement: {
    prototype: HTMLClHeadingElement;
    new (): HTMLClHeadingElement;
  };

  interface HTMLClPaperElement extends Components.ClPaper, HTMLStencilElement {}
  var HTMLClPaperElement: {
    prototype: HTMLClPaperElement;
    new (): HTMLClPaperElement;
  };

  interface HTMLClTextElement extends Components.ClText, HTMLStencilElement {}
  var HTMLClTextElement: {
    prototype: HTMLClTextElement;
    new (): HTMLClTextElement;
  };

  interface HTMLClWeatherCardElement extends Components.ClWeatherCard, HTMLStencilElement {}
  var HTMLClWeatherCardElement: {
    prototype: HTMLClWeatherCardElement;
    new (): HTMLClWeatherCardElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'cl-2-up': HTMLCl2UpElement
    'cl-avatar': HTMLClAvatarElement
    'cl-box': HTMLClBoxElement
    'cl-button-box': HTMLClButtonBoxElement
    'cl-expansion-panel': HTMLClExpansionPanelElement
    'cl-heading': HTMLClHeadingElement
    'cl-paper': HTMLClPaperElement
    'cl-text': HTMLClTextElement
    'cl-weather-card': HTMLClWeatherCardElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'cl-2-up': HTMLCl2UpElement;
    'cl-avatar': HTMLClAvatarElement;
    'cl-box': HTMLClBoxElement;
    'cl-button-box': HTMLClButtonBoxElement;
    'cl-expansion-panel': HTMLClExpansionPanelElement;
    'cl-heading': HTMLClHeadingElement;
    'cl-paper': HTMLClPaperElement;
    'cl-text': HTMLClTextElement;
    'cl-weather-card': HTMLClWeatherCardElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
