/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface ClBox {}
  interface ClBoxAttributes extends StencilHTMLAttributes {}

  interface ClPaper {}
  interface ClPaperAttributes extends StencilHTMLAttributes {}

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ClBox': Components.ClBox;
    'ClPaper': Components.ClPaper;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'cl-box': Components.ClBoxAttributes;
    'cl-paper': Components.ClPaperAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLClBoxElement extends Components.ClBox, HTMLStencilElement {}
  var HTMLClBoxElement: {
    prototype: HTMLClBoxElement;
    new (): HTMLClBoxElement;
  };

  interface HTMLClPaperElement extends Components.ClPaper, HTMLStencilElement {}
  var HTMLClPaperElement: {
    prototype: HTMLClPaperElement;
    new (): HTMLClPaperElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'cl-box': HTMLClBoxElement
    'cl-paper': HTMLClPaperElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'cl-box': HTMLClBoxElement;
    'cl-paper': HTMLClPaperElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
